//
//  WeatherStyleKit.h
//  WeatherApp
//
//  Created by RyanRosello on 4/7/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WeatherStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas1Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas4Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas6Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas7Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas8Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas9Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas10Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas11Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas13Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas18Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas20Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas21Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas22Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas23Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas24Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas25Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas26Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas27Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas28Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas29Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas30Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas31Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas32Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas33Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas34Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas35Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas36Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas37Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas38Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas39Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas40Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas42Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas43Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas77Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas79Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas80Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas81Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas82Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas83Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas78Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas2Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas3Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas41Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas44Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas45Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas46Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas47Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas48Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas49Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas50Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas51Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas52Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas53Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas54Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas55Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas56Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas57Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas58Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas59Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas60Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas61Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas62Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas63Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas64Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas65Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas67Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas68Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas69Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas70Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas71Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas72Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas73Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas74Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas75Targets;

// Generated Images
+ (UIImage*)imageOfCanvas1;
+ (UIImage*)imageOfCanvas4;
+ (UIImage*)imageOfCanvas6;
+ (UIImage*)imageOfCanvas7;
+ (UIImage*)imageOfCanvas8;
+ (UIImage*)imageOfCanvas9;
+ (UIImage*)imageOfCanvas10;
+ (UIImage*)imageOfCanvas11;
+ (UIImage*)imageOfCanvas13;
+ (UIImage*)imageOfCanvas18;
+ (UIImage*)imageOfCanvas20;
+ (UIImage*)imageOfCanvas21;
+ (UIImage*)imageOfCanvas22;
+ (UIImage*)imageOfCanvas23;
+ (UIImage*)imageOfCanvas24;
+ (UIImage*)imageOfCanvas25;
+ (UIImage*)imageOfCanvas26;
+ (UIImage*)imageOfCanvas27;
+ (UIImage*)imageOfCanvas28;
+ (UIImage*)imageOfCanvas29;
+ (UIImage*)imageOfCanvas30;
+ (UIImage*)imageOfCanvas31;
+ (UIImage*)imageOfCanvas32;
+ (UIImage*)imageOfCanvas33;
+ (UIImage*)imageOfCanvas34;
+ (UIImage*)imageOfCanvas35;
+ (UIImage*)imageOfCanvas36;
+ (UIImage*)imageOfCanvas37;
+ (UIImage*)imageOfCanvas38;
+ (UIImage*)imageOfCanvas39;
+ (UIImage*)imageOfCanvas40;
+ (UIImage*)imageOfCanvas42;
+ (UIImage*)imageOfCanvas43;
+ (UIImage*)imageOfCanvas77;
+ (UIImage*)imageOfCanvas79;
+ (UIImage*)imageOfCanvas80;
+ (UIImage*)imageOfCanvas81;
+ (UIImage*)imageOfCanvas82;
+ (UIImage*)imageOfCanvas83;
+ (UIImage*)imageOfCanvas78;
+ (UIImage*)imageOfCanvas2;
+ (UIImage*)imageOfCanvas3;
+ (UIImage*)imageOfCanvas41;
+ (UIImage*)imageOfCanvas44;
+ (UIImage*)imageOfCanvas45;
+ (UIImage*)imageOfCanvas46;
+ (UIImage*)imageOfCanvas47;
+ (UIImage*)imageOfCanvas48;
+ (UIImage*)imageOfCanvas49;
+ (UIImage*)imageOfCanvas50;
+ (UIImage*)imageOfCanvas51;
+ (UIImage*)imageOfCanvas52;
+ (UIImage*)imageOfCanvas53;
+ (UIImage*)imageOfCanvas54;
+ (UIImage*)imageOfCanvas55;
+ (UIImage*)imageOfCanvas56;
+ (UIImage*)imageOfCanvas57;
+ (UIImage*)imageOfCanvas58;
+ (UIImage*)imageOfCanvas59;
+ (UIImage*)imageOfCanvas60;
+ (UIImage*)imageOfCanvas61;
+ (UIImage*)imageOfCanvas62;
+ (UIImage*)imageOfCanvas63;
+ (UIImage*)imageOfCanvas64;
+ (UIImage*)imageOfCanvas65;
+ (UIImage*)imageOfCanvas67;
+ (UIImage*)imageOfCanvas68;
+ (UIImage*)imageOfCanvas69;
+ (UIImage*)imageOfCanvas70;
+ (UIImage*)imageOfCanvas71;
+ (UIImage*)imageOfCanvas72;
+ (UIImage*)imageOfCanvas73;
+ (UIImage*)imageOfCanvas74;
+ (UIImage*)imageOfCanvas75;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
