//
//  WeatherStyleKit.h
//  WeatherApp
//
//  Created by RyanRosello on 2/2/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WeatherStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas1Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas4Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas6Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas7Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas8Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas9Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas10Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas11Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas13Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas2Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas3Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas5Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas15Targets;

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas4;
+ (void)drawCanvas6;
+ (void)drawCanvas7;
+ (void)drawCanvas8;
+ (void)drawCanvas9;
+ (void)drawCanvas10;
+ (void)drawCanvas11;
+ (void)drawCanvas13;
+ (void)drawCanvas2;
+ (void)drawCanvas3;
+ (void)drawCanvas5;
+ (void)drawCanvas12;
+ (void)drawCanvas14;
+ (void)drawCanvas15;
+ (void)drawCanvas16;
+ (void)drawCanvas17;

// Generated Images
+ (UIImage*)imageOfCanvas1;
+ (UIImage*)imageOfCanvas4;
+ (UIImage*)imageOfCanvas6;
+ (UIImage*)imageOfCanvas7;
+ (UIImage*)imageOfCanvas8;
+ (UIImage*)imageOfCanvas9;
+ (UIImage*)imageOfCanvas10;
+ (UIImage*)imageOfCanvas11;
+ (UIImage*)imageOfCanvas13;
+ (UIImage*)imageOfCanvas2;
+ (UIImage*)imageOfCanvas3;
+ (UIImage*)imageOfCanvas5;
+ (UIImage*)imageOfCanvas15;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
